In [ ]:
df_female = pd.read_csv('Female-Names.csv')
df_male = pd.read_csv('Male-Names.csv')

In [ ]:
df_male

name gender    race
0                   barjraj      m  indian
1              ramdin verma      m  indian
2           sharat chandran      m  indian
3           birender mandal      m  indian
4                      amit      m  indian
5                    kushal      m  indian
6                     kasid      m  indian
7              shiv prakash      m  indian
8              vikram singh      m  indian
9                    sanjay      m  indian
10                     abhi      m  indian
11           ram dutt gupta      m  indian
12             khadak singh      m  indian
13             gurmit singh      m  indian
14               chanderpal      m  indian
15                     aman      m  indian
16                  khursid      m  indian
17                   rajeev      m  indian
18                  durgesh      m  indian
19              nahar singh      m  indian
20                ram kumar      m  indian
21              sunder paal      m  indian
22          maansingh aswal      m  indian
23                    rohit      m  indian
24                    rohit      m  indian
25                   sparsh      m  indian
26                  santosh      m  indian
27                  santosh      m  indian
28         punit khandelwal      m  indian
29                   dinesh      m  indian
...                     ...    ...     ...
14810         manish bansal      m  indian
14811          chander bhan      m  indian
14812                   jai      m  indian
14813  gurmeet singh @ golu      m  indian
14814                 bablu      m  indian
14815                 pinki      m  indian
14816        surender singh      m  indian
14817        vikram bahadur      m  indian
14818            kapil dutt      m  indian
14819                mukesh      m  indian
14820              harender      m  indian
14821           vinay kumar      m  indian
14822        surendra singh      m  indian
14823          bharat singh      m  indian
14824         vishal ahemad      m  indian
14825             ghanshyam      m  indian
14826                rayish      m  indian
14827                 ayush      m  indian
14828            sunder jha      m  indian
14829       bhupender singh      m  indian
14830         pradeep kumar      m  indian
14831           ajeet singj      m  indian
14832          rajesh kumar      m  indian
14833      ashok shrivastav      m  indian
14834         jarnail singh      m  indian
14835                  avid      m  indian
14836           vinod kumar      m  indian
14837             raj kumar      m  indian
14838        sanjya chhetri      m  indian
14839            raj kishor      m  indian

[14840 rows x 3 columns]

In [ ]:
df = pd.concat([df_female , df_male])

In [ ]:
char2idx = {}
char_set = [' ', '.','END', 'a', 'c', 'b', 'e', 'd', 'g', 'f', 'i', 'h', 'k', 'j', 'm', 'l', 'o', 'n', 'q', 'p', 's', 'r', 'u', 't', 'w', 'v', 'y', 'x', 'z']
index = 0
for ch in char_set:
    char2idx[ch] = index
    index += 1
   

In [ ]:
def should_keep(word):
    if len(word) > 19:
        return False
    for ch in word:
        if ch not in set(char_set):
            return False
    return True

In [ ]:
def clean(word):
    word = str(word)
    char_set = [' ', '.','END', 'a', 'c', 'b', 'e', 'd', 'g', 'f', 'i', 'h', 'k', 'j', 'm', 'l', 'o', 'n', 'q', 'p', 's', 'r', 'u', 't', 'w', 'v', 'y', 'x', 'z']
    name = word.lower()
    if should_keep(name):
        return name
    else:
        return None

In [ ]:
df.name = df.name.apply(lambda x : clean(x))

In [ ]:
df = df.dropna()

In [ ]:
max_word_len = 20
def convert_one_hot(word):
    word_chars = []
    
    
    for ch in word:
        print(word)
        one_hot_vec = np.zeros(len(char_set),)
        one_hot_vec[char2idx[ch]] = 1
        word_chars.append(one_hot_vec)
    
    
    for _ in range(max_word_len-len(word)):
        one_hot_vec = np.zeros(len(char_set),)
        one_hot_vec[char2idx['END']] = 1
        word_chars.append(one_hot_vec)
    
    
    word_chars = np.array(word_chars)
    return word_chars

In [ ]:
words = []
labels = []
for n , g in df.drop('race' , axis = 1).itertuples(index=False):
    words.append(convert_one_hot(n))
    labels.append(g)

In [ ]:
words = np.array(words)
labels = np.array(labels)

In [ ]:
words.shape

(27980, 20, 29)

In [ ]:
ohe = OneHotEncoder()
y = ohe.fit_transform(labels.reshape(-1 , 1)).todense()

In [ ]:
y[:10]

matrix([[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]])

In [ ]:
model = Sequential()
model.add(LSTM(64 , input_shape = (20 , 29)  , return_sequences = True))
model.add(LSTM(64))
model.add(Dropout(.3))
model.add(Dense(2 , activation='sigmoid'))
model.summary()

NameError: ignored

In [ ]:
model.compile(optimizer='rmsprop' , loss = 'binary_crossentropy' , metrics = ['acc'])

NameError: ignored

In [ ]:
train_test_split?

In [ ]:
model = Sequential()
model.add(LSTM(128 , input_shape = (20 , 29)  , return_sequences = True))
model.add(LSTM(64))
model.add(Dropout(.3))
model.add(Dense(2 , activation='sigmoid'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 20, 128)           80896     
_________________________________________________________________
lstm_4 (LSTM)                (None, 64)                49408     
_________________________________________________________________
dropout_2 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 130       
Total params: 130,434
Trainable params: 130,434
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='rmsprop' , loss = 'binary_crossentropy' , metrics = ['acc'])

In [ ]:
train_test_split?

In [ ]:
model = Sequential()
model.add(LSTM(64 , input_shape = (20 , 29)  , return_sequences = True))
model.add(LSTM(64))
model.add(Dropout(.3))
model.add(Dense(2 , activation='sigmoid'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_5 (LSTM)                (None, 20, 64)            24064     
_________________________________________________________________
lstm_6 (LSTM)                (None, 64)                33024     
_________________________________________________________________
dropout_3 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 130       
Total params: 57,218
Trainable params: 57,218
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='rmsprop' , loss = 'binary_crossentropy' , metrics = ['acc'])

In [ ]:
model = Sequential()
model.add(LSTM(64 , input_shape = (20 , 29)  , return_sequences = True))
model.add(LSTM(64))
model.add(Dropout(.3))
model.add(Dense(2 , activation='sigmoid'))
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_7 (LSTM)                (None, 20, 64)            24064     
_________________________________________________________________
lstm_8 (LSTM)                (None, 64)                33024     
_________________________________________________________________
dropout_4 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 130       
Total params: 57,218
Trainable params: 57,218
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='rmsprop' , loss = 'binary_crossentropy' , metrics = ['acc'])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(words, y, test_size=0.33, random_state=42)

In [ ]:
model.fit(X_train , y_train , epochs = 10)

Epoch 1/10
18746/18746 [==============================] - 57s 3ms/step - loss: 0.5181 - acc: 0.7473
Epoch 2/10
18746/18746 [==============================] - 51s 3ms/step - loss: 0.3983 - acc: 0.8278
Epoch 3/10
18746/18746 [==============================] - 51s 3ms/step - loss: 0.3422 - acc: 0.8606
Epoch 4/10
18746/18746 [==============================] - 51s 3ms/step - loss: 0.3038 - acc: 0.8802
Epoch 5/10
18746/18746 [==============================] - 51s 3ms/step - loss: 0.2775 - acc: 0.8929
Epoch 6/10
18746/18746 [==============================] - 52s 3ms/step - loss: 0.2582 - acc: 0.9044
Epoch 7/10
18746/18746 [==============================] - 52s 3ms/step - loss: 0.2393 - acc: 0.9128
Epoch 8/10
18746/18746 [==============================] - 52s 3ms/step - loss: 0.2257 - acc: 0.9198
Epoch 9/10
18746/18746 [==============================] - 52s 3ms/step - loss: 0.2139 - acc: 0.9265
Epoch 10/10
18746/18746 [==============================] - 52s 3ms/step - loss: 0.2046 - acc: 0.9284

In [ ]:
model.evaluate(X_test , y_test)

9234/9234 [==============================] - 10s 1ms/step


[0.2331865997587625, 0.9205653021571594]

In [ ]:
name = 'shreya'
model.predict(convert_one_hot(name).reshape(1 , 20 , 29))

array([[0.9699597 , 0.03057231]], dtype=float32)

In [ ]:
name = 'anuj'
model.predict(convert_one_hot(name).reshape(1 , 20 , 29))

array([[0.08267006, 0.90687656]], dtype=float32)

In [ ]:
name = 'lovely'
model.predict(convert_one_hot(name).reshape(1 , 20 , 29))

array([[0.36418867, 0.63096476]], dtype=float32)

In [ ]:
name = 'sweety'
model.predict(convert_one_hot(name).reshape(1 , 20 , 29))

array([[0.6060676 , 0.38968748]], dtype=float32)